### ISSUE TITLE
communication_constraints_violation

### ISSUE THREAD

**Issue by seivazi** [dougsm/mvp_grasp#9]
Hi,
After setting up two ROS machine.
PC1 (master) with realtime kernel
-roscore
- roslaunch mvp_grasping robot_bringup.launch
....Listening to '/move_group/monitored_planning_scene'

PC2 (client)
- roslaunch mvp_grasping wrist_realsense.launch

Following error appear in PC1:
[ERROR] [1580222432.680721801]: libfranka: Move command aborted: motion aborted by reflex! ["communication_constraints_violation"]
control_command_success_rate: 0.52

Any suggestion?

**Comment by dougsm** [comment]
This error
`["communication_constraints_violation"]
control_command_success_rate: 0.52`
Happens when the network connection between the RT kernel machine and the panda is not able to transmit the control signal at 1khz as required by the panda. Normally it requires a dedicated 1Gbps network connection.  Are you sharing network bandwidth with ROS (and especially streaming camera images)? Depending on your networking equipment, it can saturate and fail. 
I would recommend having one network connection for ROS/internet etc, and a separate, dedicated network link to the panda. I believe this is also what is recommended by Franka.  This is the setup that we use and it works reliably.

**Comment by seivazi** [comment]
You are right! Once I follow your instruction The error went a way :)
